export const tokens = [
  'Ý Nghĩa Chi Tiết Của "Aberration"\n',
  '\n',
  '"Aberration" là một danh từ (noun) có nguồn gốc từ tiếng Latinh aberrāre (nghĩa là "đi lạc, đi chệch hướng"), dùng để chỉ sự sai lệch, khác thường, hoặc chệch khỏi cái gì được coi là bình thường, tiêu chuẩn, hoặc hợp lý.\n',
  '\n',
  '1. Ngữ Cảnh Chung (Hành vi/Hiện tượng Sai lệch)\n',
  'Trong sử dụng hàng ngày, "aberration" dùng để mô tả một sự kiện, hành vi, hoặc hiện tượng bất thường, không mong đợi, và không phù hợp với quy tắc, thông lệ, hoặc tính chất quen thuộc của một người/vật/hiện tượng. Nó thường ngụ ý rằng sự sai lệch này là tạm thời hoặc ngoại lệ.\n',
  '\n',
  'Ví dụ: "Thành công của dự án này trong bối cảnh nền kinh tế suy thoái được coi là một aberration (sự bất thường) về mặt thống kê."\n',
  '\n',
  'Ví dụ: "Hành động thiếu suy nghĩ đó chỉ là một aberration (hành vi sai lệch) nhất thời và không đại diện cho tính cách thường ngày của anh ấy."\n',
  '\n',
  '2. Ngữ Cảnh Khoa học và Kỹ thuật\n',
  'Trong lĩnh vực khoa học, ý nghĩa của từ này trở nên cụ thể và kỹ thuật hơn: \n',
  'A. Quang sai (Optical Aberration)\n',
  'Đây là thuật ngữ cốt lõi trong Quang học (Optics), mô tả một lỗi kỹ thuật của hệ thống quang học (như thấu kính hoặc gương) khiến các tia sáng không hội tụ tại một điểm duy nhất, hoàn hảo. Điều này dẫn đến hình ảnh thu được bị mờ, méo mó, hoặc có viền màu.\n',
  '\n',
  'Quang sai màu (Chromatic Aberration): Là lỗi do thấu kính khúc xạ các màu sắc khác nhau (các bước sóng khác nhau) ở các mức độ khác nhau, khiến chúng hội tụ tại các điểm khác nhau. Kết quả là hình ảnh có viền màu sắc khó chịu.\n',
  '\n',
  'Cầu sai (Spherical Aberration): Là lỗi do các tia sáng đi qua rìa thấu kính hội tụ tại một điểm khác với các tia đi qua gần tâm thấu kính.\n',
  '\n',
  'B. Bất thường Nhiễm sắc thể (Chromosomal Aberration)\n',
  'Trong Sinh học và Di truyền học, thuật ngữ này chỉ những thay đổi bất thường về cấu trúc (ví dụ: bị mất, lặp, hoặc đảo đoạn) hoặc số lượng (ví dụ: có thêm hoặc thiếu) của nhiễm sắc thể trong tế bào. Đây là nguyên nhân gốc rễ của nhiều hội chứng và bệnh lý di truyền.\n',
  '\n',
  '3. Ngữ Cảnh Thiên văn học (Aberration of Light)\n',
  'Đây là sự dịch chuyển biểu kiến (apparent shift) của vị trí một ngôi sao hoặc vật thể thiên văn do sự kết hợp của: \n',
  '- Vận tốc có giới hạn của ánh sáng.\n',
  '- Vận tốc của người quan sát (thường là Trái Đất quay quanh Mặt Trời).\n',
];
